// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXFFYUcnVELTAbtcVTYI9z5XtzOsHoxo',
    appId: '1:385932001708:web:d3fe861017e59079b7ba09',
    messagingSenderId: '385932001708',
    projectId: 'bynry-1471e',
    authDomain: 'bynry-1471e.firebaseapp.com',
    storageBucket: 'bynry-1471e.appspot.com',
    measurementId: 'G-KG989B8K1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClF6wYZwYyr514iL7gcChgvYJvUgkA1nU',
    appId: '1:385932001708:android:0d5b7908557581edb7ba09',
    messagingSenderId: '385932001708',
    projectId: 'bynry-1471e',
    storageBucket: 'bynry-1471e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi--owa_u4DrAu4qzBthi6f64hUAIfs7w',
    appId: '1:385932001708:ios:2d96dbef90b4ac06b7ba09',
    messagingSenderId: '385932001708',
    projectId: 'bynry-1471e',
    storageBucket: 'bynry-1471e.appspot.com',
    iosBundleId: 'com.example.bynryCasestudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi--owa_u4DrAu4qzBthi6f64hUAIfs7w',
    appId: '1:385932001708:ios:2d96dbef90b4ac06b7ba09',
    messagingSenderId: '385932001708',
    projectId: 'bynry-1471e',
    storageBucket: 'bynry-1471e.appspot.com',
    iosBundleId: 'com.example.bynryCasestudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiXFFYUcnVELTAbtcVTYI9z5XtzOsHoxo',
    appId: '1:385932001708:web:c2270d02ff2936c7b7ba09',
    messagingSenderId: '385932001708',
    projectId: 'bynry-1471e',
    authDomain: 'bynry-1471e.firebaseapp.com',
    storageBucket: 'bynry-1471e.appspot.com',
    measurementId: 'G-2RLH45BRNP',
  );
}
